# 检查配置文件变动的时间间隔
refresh_rate = "30 seconds"

[appenders.stdout]
kind = "console"
encoder.pattern = "{d(%Y-%m-%d %H:%M:%S %Z)(local)} {h({l:>5.5})} {P} [{T:>20.20}] {h({M:>24.24})}: {m}{n}"

[appenders.requests]
kind = "rolling_file"
path = "log/server.log"
encoder.pattern = "{d(%Y-%m-%d %H:%M:%S %Z)(local)} {h({l:>5.5})} {P} [{T:>20.20}] {h({M:>24.24})}: {m}{n}"
policy.kind = "compound"
policy.trigger.kind = "size"
policy.trigger.limit = "20 mb"
policy.roller.kind = "fixed_window"
policy.roller.pattern = 'log/server.log.{{}}'
policy.roller.base = 1
policy.roller.count = 5

[root]
level = "debug"
appenders = ["stdout", "requests"]

[loggers]
#"sqlx::query".level = "debug"
"hyper::proto::h1".level = "info"
